module.exports = {
addAndViewItem: true,
addAndUpdateBrand: true,
brandListing: true,
addStock: true,
viewStock: true,
stockSummery: true,
stockReport: true,
showDamage: true,
addInvoice: true,
viewInvoice: true,
invoiceReport: true,
returnInvoice: true,
colorModelWise: true,
updateAndCreateLedger: true,
recieveMoneyReport: true,
ledgerReport: true,
updateAndCreateBank: true,
bankListing: true,
bankLedger: true,
updateAndCreatePettyCash: true,
pettyCashListing: true,
uploadPdf: true,
pdfListing: true,
updateAndCreateCustomer: true,
customerListing: true
}